# data-intelligence/deploy/kafka-cluster.yaml
# This manifest is designed for a GitOps controller like Argo CD or Flux.
# It declaratively defines a Helm release for Kafka.
apiVersion: v1
kind: Namespace
metadata:
  name: kafka
---
# This defines the source repository for the Helm chart
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system # Assumes the GitOps controller runs here
spec:
  interval: 30m
  url: https://charts.bitnami.com/bitnami
---
# This defines the actual deployment of the Kafka chart
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: kafka
      version: "26.2.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    # Minimal configuration for zero-cost footprint
    zookeeper:
      replicaCount: 1
      resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: 250m, memory: 256Mi } }
    controller:
      replicaCount: 1
      resources: { requests: { cpu: 100m, memory: 128Mi }, limits: { cpu: 250m, memory: 256Mi } }
    broker:
      replicaCount: 1
      resources: { requests: { cpu: 100m, memory: 256Mi }, limits: { cpu: 500m, memory: 512Mi } }
