# data-intelligence/deploy/vault-server.yaml
# This manifest is designed for a GitOps controller like Argo CD or Flux.

# Defines the source repository for the HashiCorp Helm chart
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system # Assumes the GitOps controller runs here
spec:
  interval: 30m
  url: https://helm.releases.hashicorp.com
---
# Defines the actual deployment of the Vault chart
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: default # Deploying into the default namespace for local testing
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.27.0" # Use a specific, stable version
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    # UI is enabled for easier management
    ui:
      enabled: true
    # Configure Vault to run in a standalone, single-server mode
    # This is not HA, but it is not insecure 'dev' mode either.
    server:
      standalone:
        enabled: true
      # Use a persistent volume to store data, making it production-hardened
      dataStorage:
        enabled: true
        size: 1Gi # A small size for our free-tier project
        storageClass: null # Use minikube's default
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi
